### ISSUE TITLE
Exception when trying to load sstables

### ISSUE THREAD

**Issue by jpoblete** [tolbertam/sstable-tools#68]
Can't seem to get it to work

```
[automaton@ip-172-31-9-120 device_monitoring_timestamps]$ pwd
/home/automaton/36134/sstables_10.246.171.127/health/device_monitoring_timestamps
[automaton@ip-172-31-9-120 device_monitoring_timestamps]$ dse -v
5.0.2
[automaton@ip-172-31-9-120 device_monitoring_timestamps]$ ls -la
total 19320
drwxrwxr-x 2 automaton automaton     4096 Aug 28 17:18 .
drwxrwxr-x 3 automaton automaton     4096 Aug 28 17:17 ..
-rw-r--r-- 1 automaton automaton     9307 Aug 27 19:20 mc-7074-big-CompressionInfo.db
-rw-r--r-- 1 automaton automaton 16637579 Aug 27 19:20 mc-7074-big-Data.db
-rw-r--r-- 1 automaton automaton     2744 Aug 27 19:20 mc-7074-big-Filter.db
-rw-r--r-- 1 automaton automaton   140381 Aug 27 19:20 mc-7074-big-Index.db
-rw-r--r-- 1 automaton automaton    11047 Aug 27 19:20 mc-7074-big-Statistics.db
-rw-r--r-- 1 automaton automaton      588 Aug 27 19:20 mc-7074-big-Summary.db
-rw-r--r-- 1 automaton automaton     2587 Aug 27 20:58 mc-7075-big-CompressionInfo.db
-rw-r--r-- 1 automaton automaton  2867725 Aug 27 20:58 mc-7075-big-Data.db
-rw-r--r-- 1 automaton automaton     2368 Aug 27 20:58 mc-7075-big-Filter.db
-rw-r--r-- 1 automaton automaton    63530 Aug 27 20:58 mc-7075-big-Index.db
-rw-r--r-- 1 automaton automaton    10144 Aug 27 20:58 mc-7075-big-Statistics.db
-rw-r--r-- 1 automaton automaton      501 Aug 27 20:58 mc-7075-big-Summary.db
[automaton@ip-172-31-9-120 device_monitoring_timestamps]$ java -jar $HOME/36134/sstable-tools-3.11.0-alpha11.jar cqlsh
cqlsh> use mc-7075-big-Data.db
Using: /home/automaton/36134/sstables_10.246.171.127/health/device_monitoring_timestamps/mc-7075-big-Data.db
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.apache.cassandra.utils.NativeLibraryLinux.getpid()J
        at org.apache.cassandra.utils.NativeLibraryLinux.getpid(Native Method)
        at org.apache.cassandra.utils.NativeLibraryLinux.callGetpid(NativeLibraryLinux.java:122)
        at org.apache.cassandra.utils.NativeLibrary.getProcessID(NativeLibrary.java:394)
        at org.apache.cassandra.utils.UUIDGen.hash(UUIDGen.java:388)
        at org.apache.cassandra.utils.UUIDGen.makeNode(UUIDGen.java:367)
        at org.apache.cassandra.utils.UUIDGen.makeClockSeqAndNode(UUIDGen.java:300)
        at org.apache.cassandra.utils.UUIDGen.<clinit>(UUIDGen.java:41)
        at org.apache.cassandra.config.CFMetaData$Builder.build(CFMetaData.java:1293)
        at com.csforge.sstable.CassandraUtils.tableFromSSTable(CassandraUtils.java:263)
        at com.csforge.sstable.CassandraUtils.tableFromBestSource(CassandraUtils.java:99)
        at com.csforge.sstable.Cqlsh.doUse(Cqlsh.java:302)
        at com.csforge.sstable.Cqlsh.evalLine(Cqlsh.java:615)
        at com.csforge.sstable.Cqlsh.startShell(Cqlsh.java:252)
        at com.csforge.sstable.Cqlsh.main(Cqlsh.java:762)
        at com.csforge.sstable.Driver.main(Driver.java:22)
[automaton@ip-172-31-9-120 device_monitoring_timestamps]$ java -jar $HOME/36134/sstable-tools-3.11.0-alpha11.jar cqlsh
cqlsh> use /home/automaton/36134/sstables_10.246.171.127/health/device_monitoring_timestamps/
Using: /home/automaton/36134/sstables_10.246.171.127/health/device_monitoring_timestamps/mc-7074-big-Data.db
Using: /home/automaton/36134/sstables_10.246.171.127/health/device_monitoring_timestamps/mc-7075-big-Data.db
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.apache.cassandra.utils.NativeLibraryLinux.getpid()J
        at org.apache.cassandra.utils.NativeLibraryLinux.getpid(Native Method)
        at org.apache.cassandra.utils.NativeLibraryLinux.callGetpid(NativeLibraryLinux.java:122)
        at org.apache.cassandra.utils.NativeLibrary.getProcessID(NativeLibrary.java:394)
        at org.apache.cassandra.utils.UUIDGen.hash(UUIDGen.java:388)
        at org.apache.cassandra.utils.UUIDGen.makeNode(UUIDGen.java:367)
        at org.apache.cassandra.utils.UUIDGen.makeClockSeqAndNode(UUIDGen.java:300)
        at org.apache.cassandra.utils.UUIDGen.<clinit>(UUIDGen.java:41)
        at org.apache.cassandra.config.CFMetaData$Builder.build(CFMetaData.java:1293)
        at com.csforge.sstable.CassandraUtils.tableFromSSTable(CassandraUtils.java:263)
        at com.csforge.sstable.CassandraUtils.tableFromBestSource(CassandraUtils.java:99)
        at com.csforge.sstable.Cqlsh.doUse(Cqlsh.java:302)
        at com.csforge.sstable.Cqlsh.evalLine(Cqlsh.java:615)
        at com.csforge.sstable.Cqlsh.startShell(Cqlsh.java:252)
        at com.csforge.sstable.Cqlsh.main(Cqlsh.java:762)
        at com.csforge.sstable.Driver.main(Driver.java:22)

```

**Comment by tolbertam** [comment]
This looks very similar to Stratio/cassandra-lucene-index#345 which could have to do with incompatibilities between the version of JNA in use and the version of glibc involved.   Will need to investigate more.
